dist: bionic

services:
  - docker

sudo: required

language: python
python:
  - 3.7

env:
  global:
    - RELEASE_BRANCH="master"

before_install:
  - pip install docker
  - pip install flask
  - wget -c https://github.com/ValveSoftware/wine/archive/wine-5.11.tar.gz

install:
  - tar xf wine-5.11.tar.gz

before_script:
  - echo "******* Starting here! *******"
  - mkdir result
  - python3.7 run_web_server.py &

script:
  - python3.7 phoenicis-make.py --wine-src=$HOME/wine-wine-5.11/ --archive=$HOME/result --environment=wine_osxcross/linux/amd64 --architecture=x86 --os=linux --build

after_success:
  - echo "******* Sucess! *******"
  - ls -la result

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
